import type { AppData } from "./types";

// Deterministic ISO helper relative to "now" so the demo always looks fresh.
const now = Date.now();
const hoursAgo = (h: number) => new Date(now - h * 3600_000).toISOString();
const daysFromNow = (d: number) =>
  new Date(now + d * 86400_000).toISOString().slice(0, 10);

export const SEED: AppData = {
  members: [
    {
      id: "u_malachi",
      name: "Malachi Moak",
      role: "admin",
      department: "Creative",
      title: "Creative Director",
      email: "moakmedia2021@gmail.com",
      phone: "+1 555 0101",
      avatarColor: "#12a6db",
    },
    {
      id: "u_michael",
      name: "Pastor Michael Moak",
      role: "pastor",
      department: "Leadership",
      title: "Lead Pastor",
      email: "pastor@hillcrestag.org",
      avatarColor: "#7c3aed",
    },
    {
      id: "u_sarah",
      name: "Sarah Bennett",
      role: "lead",
      department: "Creative",
      title: "Social Media Lead",
      email: "sarah@hillcrestag.org",
      avatarColor: "#db2777",
    },
    {
      id: "u_james",
      name: "James Carter",
      role: "volunteer",
      department: "Creative",
      title: "Videographer",
      email: "james@hillcrestag.org",
      avatarColor: "#ea580c",
    },
    {
      id: "u_grace",
      name: "Grace Kim",
      role: "volunteer",
      department: "Creative",
      title: "Editor",
      email: "grace@hillcrestag.org",
      avatarColor: "#16a34a",
    },
    {
      id: "u_david",
      name: "David Nguyen",
      role: "lead",
      department: "Worship",
      title: "Worship Lead",
      email: "david@hillcrestag.org",
      avatarColor: "#0891b2",
    },
  ],

  channels: [
    {
      id: "c_announcements",
      name: "Announcements",
      kind: "announcement",
      memberIds: ["*"],
      description: "Church-wide announcements from leadership.",
    },
    {
      id: "c_creative",
      name: "Creative Team",
      kind: "team",
      memberIds: ["u_malachi", "u_michael", "u_sarah", "u_james", "u_grace"],
      description: "Video, photo, social, and design.",
    },
    {
      id: "c_social",
      name: "Social Media",
      kind: "department",
      memberIds: ["u_malachi", "u_sarah", "u_grace"],
      description: "Planning and scheduling posts.",
    },
    {
      id: "c_worship",
      name: "Worship",
      kind: "department",
      memberIds: ["u_michael", "u_david", "u_malachi"],
      description: "Sunday sets and rehearsals.",
    },
  ],

  messages: [
    {
      id: "m1",
      channelId: "c_announcements",
      authorId: "u_michael",
      body: "Team — incredible job this weekend. Attendance was up and the new sermon bumper looked amazing. Praise God! 🙌",
      createdAt: hoursAgo(20),
      pinned: true,
    },
    {
      id: "m2",
      channelId: "c_announcements",
      authorId: "u_malachi",
      body: "Reminder: all Summer on the Mount graphics are due Friday. Reach out if you need assets.",
      createdAt: hoursAgo(6),
    },
    {
      id: "m3",
      channelId: "c_creative",
      authorId: "u_sarah",
      body: "Who's filming the youth event Wednesday? Need one camera + b-roll.",
      createdAt: hoursAgo(5),
    },
    {
      id: "m4",
      channelId: "c_creative",
      authorId: "u_james",
      body: "I've got it. Bringing the A7 + gimbal. Grace, can you edit turnaround by Sat?",
      createdAt: hoursAgo(4),
    },
    {
      id: "m5",
      channelId: "c_creative",
      authorId: "u_grace",
      body: "Yep! Send me the footage Thursday night and I'll have a first cut Saturday AM.",
      createdAt: hoursAgo(3),
    },
    {
      id: "m6",
      channelId: "c_social",
      authorId: "u_malachi",
      body: "Let's batch 3 reels from Sunday's sermon. I'll drop timestamps in the schedule.",
      createdAt: hoursAgo(2),
    },
  ],

  tasks: [
    {
      id: "t1",
      title: "Summer on the Mount — sermon reel #1",
      description: "Pull 45s clip on 'blessed are the poor in spirit'.",
      stage: "editing",
      assigneeId: "u_grace",
      dueDate: daysFromNow(2),
      platform: "instagram",
      createdAt: hoursAgo(30),
    },
    {
      id: "t2",
      title: "Youth Sonic Night recap",
      description: "B-roll + interviews from Wednesday.",
      stage: "filming",
      assigneeId: "u_james",
      dueDate: daysFromNow(4),
      platform: "tiktok",
      createdAt: hoursAgo(28),
    },
    {
      id: "t3",
      title: "Weekend announcement graphic",
      stage: "review",
      assigneeId: "u_malachi",
      dueDate: daysFromNow(1),
      platform: "instagram",
      createdAt: hoursAgo(26),
    },
    {
      id: "t4",
      title: "Worship night promo video",
      description: "30s hype video for the July worship night.",
      stage: "idea",
      assigneeId: "u_sarah",
      dueDate: daysFromNow(9),
      platform: "youtube",
      createdAt: hoursAgo(20),
    },
    {
      id: "t5",
      title: "Give Now — testimony short",
      stage: "scheduled",
      assigneeId: "u_grace",
      dueDate: daysFromNow(3),
      platform: "facebook",
      createdAt: hoursAgo(18),
    },
    {
      id: "t6",
      title: "Last week's sermon full upload",
      stage: "posted",
      assigneeId: "u_malachi",
      platform: "youtube",
      createdAt: hoursAgo(50),
    },
    {
      id: "t7",
      title: "Baptism Sunday photo carousel",
      stage: "editing",
      assigneeId: "u_malachi",
      dueDate: daysFromNow(5),
      platform: "instagram",
      createdAt: hoursAgo(12),
    },
  ],

  templates: [
    {
      id: "tpl_sunday",
      name: "Sunday Service",
      category: "service",
      description: "Weekly run-of-show for a Sunday morning service.",
      items: [
        { id: "i1", label: "Confirm sermon title & scripture", role: "pastor", offsetDays: 5 },
        { id: "i2", label: "Design sermon graphic + slides", role: "lead", offsetDays: 4 },
        { id: "i3", label: "Finalize worship set list", role: "lead", offsetDays: 3 },
        { id: "i4", label: "Schedule volunteers (PCO)", role: "admin", offsetDays: 3 },
        { id: "i5", label: "Build ProPresenter / lyrics", role: "volunteer", offsetDays: 2 },
        { id: "i6", label: "Prep livestream + cameras", role: "volunteer", offsetDays: 1 },
        { id: "i7", label: "Sound check & rehearsal", role: "lead", offsetDays: 0 },
        { id: "i8", label: "Post sermon recap clip", role: "lead", offsetDays: 0 },
      ],
    },
    {
      id: "tpl_youth",
      name: "Youth Night",
      category: "youth",
      description: "Midweek youth service and hangout.",
      items: [
        { id: "i1", label: "Plan theme & message", role: "lead", offsetDays: 7 },
        { id: "i2", label: "Promo graphic + reel", role: "lead", offsetDays: 5 },
        { id: "i3", label: "Order snacks / supplies", role: "volunteer", offsetDays: 3 },
        { id: "i4", label: "Confirm games & activities", role: "volunteer", offsetDays: 2 },
        { id: "i5", label: "Set up room & tech", role: "volunteer", offsetDays: 0 },
        { id: "i6", label: "Capture photos/video for recap", role: "volunteer", offsetDays: 0 },
      ],
    },
    {
      id: "tpl_outreach",
      name: "Community Outreach",
      category: "outreach",
      description: "Serve event in the community.",
      items: [
        { id: "i1", label: "Confirm location & permits", role: "admin", offsetDays: 14 },
        { id: "i2", label: "Recruit & schedule volunteers", role: "lead", offsetDays: 10 },
        { id: "i3", label: "Promote event (social + bulletin)", role: "lead", offsetDays: 7 },
        { id: "i4", label: "Gather supplies & signage", role: "volunteer", offsetDays: 3 },
        { id: "i5", label: "Day-of setup & check-in", role: "volunteer", offsetDays: 0 },
        { id: "i6", label: "Thank-you + recap post", role: "lead", offsetDays: 0 },
      ],
    },
    {
      id: "tpl_shoot",
      name: "Video Shoot",
      category: "production",
      description: "Plan and run a creative video production day.",
      items: [
        { id: "i1", label: "Write script / shot list", role: "lead", offsetDays: 5 },
        { id: "i2", label: "Book talent & location", role: "lead", offsetDays: 4 },
        { id: "i3", label: "Prep gear (charge, cards, audio)", role: "volunteer", offsetDays: 1 },
        { id: "i4", label: "Film day", role: "volunteer", offsetDays: 0 },
        { id: "i5", label: "Back up footage to OneDrive", role: "volunteer", offsetDays: 0 },
        { id: "i6", label: "Edit + review", role: "volunteer", offsetDays: -3 },
      ],
    },
  ],

  events: [
    {
      id: "ev_sunday",
      title: "Sunday Service — Summer on the Mount Pt.3",
      category: "service",
      date: daysFromNow(4),
      time: "10:00 AM",
      location: "Main Auditorium",
      ownerId: "u_michael",
      templateId: "tpl_sunday",
      notes: "Communion this week. Baptisms after service.",
      createdAt: hoursAgo(40),
      tasks: [
        { id: "e1", label: "Confirm sermon title & scripture", done: true, assigneeId: "u_michael" },
        { id: "e2", label: "Design sermon graphic + slides", done: true, assigneeId: "u_malachi" },
        { id: "e3", label: "Finalize worship set list", done: true, assigneeId: "u_david" },
        { id: "e4", label: "Schedule volunteers (PCO)", done: false, assigneeId: "u_malachi", dueDate: daysFromNow(1) },
        { id: "e5", label: "Build ProPresenter / lyrics", done: false, assigneeId: "u_grace", dueDate: daysFromNow(2) },
        { id: "e6", label: "Prep livestream + cameras", done: false, assigneeId: "u_james", dueDate: daysFromNow(3) },
        { id: "e7", label: "Sound check & rehearsal", done: false, assigneeId: "u_david", dueDate: daysFromNow(4) },
        { id: "e8", label: "Post sermon recap clip", done: false, assigneeId: "u_sarah", dueDate: daysFromNow(4) },
      ],
    },
    {
      id: "ev_youth",
      title: "HCYOUTH Sonic Night",
      category: "youth",
      date: daysFromNow(6),
      time: "7:00 PM",
      location: "Sonic Drive-In",
      ownerId: "u_sarah",
      templateId: "tpl_youth",
      createdAt: hoursAgo(30),
      tasks: [
        { id: "e1", label: "Plan theme & message", done: true, assigneeId: "u_sarah" },
        { id: "e2", label: "Promo graphic + reel", done: true, assigneeId: "u_sarah" },
        { id: "e3", label: "Order snacks / supplies", done: false, assigneeId: "u_james", dueDate: daysFromNow(3) },
        { id: "e4", label: "Confirm games & activities", done: false, assigneeId: "u_grace", dueDate: daysFromNow(4) },
        { id: "e5", label: "Set up room & tech", done: false, assigneeId: "u_james", dueDate: daysFromNow(6) },
        { id: "e6", label: "Capture photos/video for recap", done: false, assigneeId: "u_james", dueDate: daysFromNow(6) },
      ],
    },
    {
      id: "ev_baptism",
      title: "Baptism Sunday",
      category: "special",
      date: daysFromNow(11),
      time: "10:00 AM",
      location: "Main Auditorium",
      ownerId: "u_michael",
      createdAt: hoursAgo(15),
      tasks: [
        { id: "e1", label: "Collect baptism sign-ups", done: true, assigneeId: "u_michael" },
        { id: "e2", label: "Order towels & robes", done: false, assigneeId: "u_grace", dueDate: daysFromNow(5) },
        { id: "e3", label: "Film testimonies", done: false, assigneeId: "u_james", dueDate: daysFromNow(8) },
        { id: "e4", label: "Photo carousel + recap", done: false, assigneeId: "u_malachi", dueDate: daysFromNow(11) },
      ],
    },
  ],
};
